language: php
dist: xenial
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
php:
  - 5.6
  - 7.2
  - 7.3
# Trigger a push build on master, next and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
addons:
  apt:
    update: true
before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
install:
  - travis_retry composer global require dealerdirect/phpcodesniffer-composer-installer roave/security-advisories:dev-master squizlabs/php_codesniffer phpcompatibility/php-compatibility
script:
  - npm run phpCompatibility
  - npm run codeCheck
jobs:
  include:
    - stage: release
      node_js: lts/*
      before_install:
        - export TRAVIS_NODE_VERSION="lts/*"
      install:
        - rm -rf ~/.nvm
        - git clone https://github.com/creationix/nvm.git ~/.nvm
        - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
        - source ~/.nvm/nvm.sh
        - nvm install $TRAVIS_NODE_VERSION
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release
