name: Linting

on:
  push:
    branches:
      - dependabot/**

  pull_request:
    types:
      - opened
      - synchronize

  workflow_call:

jobs:
  test:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v4
        env:
          FILTER_REGEX_INCLUDE: "/modules/*|/resources/*|/tests/*|updateVersion.sh"
          DEFAULT_BRANCH: master
          VALIDATE_PHP: true
          VALIDATE_PHP_PHPCS: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
